### PR TITLE
Add support for fish shell

### PR DESCRIPTION
**Pull request by kimusan**
Provides --fish for (un)install scripts + fish function file. Updates readme

### CODE REVIEW

**Comment by kimusan** [comment]
I can see you added support for non-sudo installations while I made this. It can be easily done with fish as well. function file (fzf-help.fish) goes to ~/.config/fish/functions/ and the other files can be put where you install them for bash. That should be enough

**Comment by BartSte** [comment]
Thanks. I'll look into it.

**Comment by BartSte** [comment]
I merged you request into the `develop` branch, and made some changes. Can you take a look? 

I also had a question, when running the `fzf-help.fish` function I get the following error:
image

Most likely, I broke this during the merge. What was you idea on getting the correct value for the `$this_dir` variable?

**Comment by kimusan** [comment]
I think this is my mistake. It is mostly just a conversion of how it was done for bash but since all files are in the same place for bash but not for fish, this would be a bit different. 
Basically I guess it should just point to the installation location for the fxf-select-option file etc. so /usr/share/fzf-help/


copying the scripts to /etc/fish/functions/ would seem a bit messy so I would think they should be separated.

**Comment by BartSte** [comment]
Ah oke, I was in doubt since I never used fish before. Thanks for your help.

**Comment by kimusan** [comment]
I guess the "this_dir" will have to check if the /usr/share/fzf-help exists, and then it should just be set to that one. The rest of the merge looks ok to me. 
I can see you caught my copy-paste error in the README - nice catch.

**Comment by BartSte** [comment]
Fish shell is now supported!

**Comment by BartSte** [comment]
Thanks for helping.

**Pull request closed without merging**
